name: C Build and Run

on:
  push:
    paths:
      - '**/*.c'
      - '**/.*yml'
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit_message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get insatll -y build-essential

      - name: Compile the code
        run: gcc Prime_Number_Detector.c -o PND

      - name: Run the Code-1
        run: |
          echo -e "Run Result:\n" > Test-Run-Result/Result.txt
          echo "1" | ./PND >> Test-Run-Result/Result.txt

      - name: Run the Code-2
        run: |
          echo -e "\n\n" >> Test-Run-Result/Result.txt
          echo "2" | ./PND >> Test-Run-Result/Result.txt

      - name: Run the Code-3
        run: |
          echo -e "\n\n" >> Test-Run-Result/Result.txt
          echo "4" | ./PND >> Test-Run-Result/Result.txt

      - name: Upload Prime Number Detector Test Run Results to Repo
        uses: actions/upload-artifact@v4
        with:
          name: Push Prime Number Detector Test-Run-Result
          path: Test-Run-Result/Result.txt
      - name: Push Result.txt to Repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add Test-Run-Result/Result.txt
          git commit -m "Update Prime Number Detector output [skip ci]" || echo "No changes to commit"
          git push
